### ISSUE TITLE
Pdf tags

### ISSUE THREAD

**Issue by ayhama16** [ItsAhmedAtef/PDFCleaner#1]
Hi, thank you so much for this code!

Do you know something about this problem? Do you know how to modify tags in pdf? I want to group some tags in it.

https://stackoverflow.com/questions/69416960/find-and-replace-or-remove-tags-adobe-acrobat

Thank you so much!

**Comment by ItsAhmedAtef** [comment]
Hi ayhama16 
As far as i know about PDF's format, That the contents of the tags are in Objects streams.
I believe that these Objects has unique identifiers like:
- links => /URI(somelinkhere)
- textboxes => /TextBox
- Images => /Image
- H1 => /H1
...and so on.
example: https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF13
```
32 0 obj
<<
  /S/URI                                       %Action type (required), must be URI for a URI action
  /URI(http://www.boston.com/business/technology/)  %Uniform resource identifier(required), the URI to be resolved
>>
endobj
```

example 2:
```
449 0 obj
<< 
/S /TextBox 
/Alt (Text Box: Figure 3. Structure Tree from a sample PDF. )
/P 309 0 R 
/K 305 0 R 
>> 
endobj
```
